name: huevo_parser
description: A tiny parser combinator
version: 1.0.0
author: Lan, Yi-Tin <lanyitin@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  tuple: ^1.0.3
