name: huevo
description: A basic compiler infrastructure for Learning how to create a compile without any compiler's compiler
version: 1.0.0-DEV
homepage: https://github.com/lanyitin/huevo-dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  tuple: ^1.0.3
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

